../design/fixedpoint_multiplier.sv
../design/fixedpoint_adder.sv
../design/fixedpoint_formatter.sv
../design/process_element.sv
../design/counter.sv
../design/pe_top.sv
../design/accelerator_FSM.sv
../design/pa_top.sv
../design/shift_buffer.sv
../design/MulAdd_top.sv
../design/clk_syncer.sv

../testbench/tb_fixedpoint_multiplier.sv
../testbench/tb_fixedpoint_formatter.sv
../testbench/tb_process_element.sv
../testbench/tb_counter.sv
../testbench/tb_pe_top.sv
../testbench/tb_FSM.sv
../testbench/tb_pa_top.sv
../testbench/tb_shift_buffer.sv
../testbench/tb_MulAdd_top.sv