/home/public/workspace/EE218/FinalProject/design/fixedpoint_multiplier.sv
/home/public/workspace/EE218/FinalProject/design/fixedpoint_adder.sv
/home/public/workspace/EE218/FinalProject/design/fixedpoint_formatter.sv
/home/public/workspace/EE218/FinalProject/design/process_element.sv
/home/public/workspace/EE218/FinalProject/design/counter.sv
/home/public/workspace/EE218/FinalProject/design/pe_top.sv
/home/public/workspace/EE218/FinalProject/design/accelerator_FSM.sv
/home/public/workspace/EE218/FinalProject/design/pa_top.sv
/home/public/workspace/EE218/FinalProject/design/shift_buffer.sv
/home/public/workspace/EE218/FinalProject/design/MulAdd_top.sv
/home/public/workspace/EE218/FinalProject/design/clk_syncer.sv

/home/public/workspace/EE218/FinalProject/testbench/tb_fixedpoint_multiplier.sv
/home/public/workspace/EE218/FinalProject/testbench/tb_fixedpoint_formatter.sv
/home/public/workspace/EE218/FinalProject/testbench/tb_process_element.sv
/home/public/workspace/EE218/FinalProject/testbench/tb_counter.sv
/home/public/workspace/EE218/FinalProject/testbench/tb_pe_top.sv
/home/public/workspace/EE218/FinalProject/testbench/tb_FSM.sv
/home/public/workspace/EE218/FinalProject/testbench/tb_pa_top.sv
/home/public/workspace/EE218/FinalProject/testbench/tb_shift_buffer.sv
/home/public/workspace/EE218/FinalProject/testbench/tb_MulAdd_top.sv